"""
GEAR_LATTICE_THEORY — full lattice field theory derivation of the gear model on the Laves graph
nos3bl33d
"""
import math
import numpy as np

phi = (1 + math.sqrt(5)) / 2
d = 3; p = 5; V = 20; E = 30; F = 12; chi = 2
L4 = 7; dp = 15; b0 = 11

print("GEAR LATTICE FIELD THEORY")
print("=" * 60)
print()

# THE LAGRANGIAN
print("THE LAGRANGIAN:")
print()
print("  L = (1/2) * sum_i I_i * dot(theta)_i^2")
print("    - phi * sum_{<i,j>} cos(theta_i + theta_j)")
print()
print("  Laves graph. d=3 neighbors. Bipartite. Chiral.")
print("  J = phi. I_i = moment of inertia (mass).")
print()

# STEP 1: Sublattice transformation
print("STEP 1: SUBLATTICE TRANSFORMATION")
print("-" * 50)
print()
print("  Laves graph is bipartite: sublattices A and B.")
print("  Transform: theta_j -> pi - theta_j for j in B.")
print("  cos(theta_i + theta_j) -> cos(theta_i + pi - theta_j)")
print("                         = -cos(theta_i - theta_j)")
print()
print("  H_anti = -phi * sum cos(theta_i + theta_j)")
print("  H_ferro = +phi * sum cos(theta_i - theta_j)")
print("  = standard ferromagnetic XY with J = phi")
print()

# STEP 2: Expand around ordered state
print("STEP 2: SPIN-WAVE EXPANSION")
print("-" * 50)
print()
print("  Ground state: all theta_i = 0 (after sublattice transform)")
print("  Fluctuation: theta_i = delta_i (small)")
print()
print("  cos(delta_i - delta_j) ~ 1 - (delta_i - delta_j)^2/2")
print()
print("  S_free = phi/2 * sum_{<i,j>} (delta_i - delta_j)^2")
print("         + (1/2) * sum_i (d_t delta_i)^2")
print()
print("  = (1/2) * delta^T (phi*L + d_t^2) delta")
print()
print("  L = graph Laplacian of Laves graph")
print()

# STEP 3: Propagator
print("STEP 3: PROPAGATOR (FORCES)")
print("-" * 50)
print()
print("  Fourier transform on Laves graph -> momentum space")
print("  G(k, omega) = 1 / (phi * lambda(k) + omega^2)")
print()
print("  Dispersion: omega^2 = phi * lambda(k)")
print("  For small k: lambda(k) ~ v^2 * k^2")
print("  -> omega^2 = phi * v^2 * k^2")
print("  -> E^2 = (c_eff)^2 * p^2  where c_eff = v*sqrt(phi)")
print()
print("  MASSLESS RELATIVISTIC DISPERSION.")
print("  Speed of light = lattice velocity * sqrt(phi).")
print()

# STEP 4: What are the particles?
print("STEP 4: PARTICLES = TOPOLOGICAL DEFECTS")
print("-" * 50)
print()
print("  XY model has VORTICES: points where theta winds by 2*pi.")
print("  On the Laves graph: smallest loop = 10 edges = 2p.")
print()
print("  A vortex around a 10-loop:")
print("    phase change per edge = 2*pi/10 = pi/5 = 36 degrees")
print("    = the golden angle complement (360/10 = 36)")
print()
print("  Vortex charge: n = integer (winding number)")
print("  n = +1: particle. n = -1: antiparticle.")
print()
print("  Vortex energy (2D XY):")
print("    E = pi * J * n^2 * ln(R/a)")
print("    = pi * phi * ln(R/a)")
print()
print("  In 3D (Laves graph): vortices are LINES (strings)")
print("    String tension: sigma = pi * phi (per unit length)")
print(f"    = {math.pi * phi:.4f}")
print()

# STEP 5: Confinement
print("STEP 5: CONFINEMENT (STRONG FORCE)")
print("-" * 50)
print()
print("  Below BKT transition (low T):")
print("    Vortex-antivortex pairs BOUND by logarithmic potential")
print("    = CONFINEMENT. Quarks can't escape.")
print()
print("  Above BKT transition (high T):")
print("    Free vortices. DECONFINEMENT. Quark-gluon plasma.")
print()
Tc = d * phi / (2 * math.log(2))
print(f"  BKT temperature (Bethe approx): T_BKT = d*phi/(2*ln(2))")
print(f"    = {Tc:.4f}")
print()

# STEP 6: Gravity from variable inertia
print("STEP 6: GRAVITY (VARIABLE INERTIA)")
print("-" * 50)
print()
print("  Massive gear: I_i >> 1 at vertex i.")
print("  This MODIFIES the local propagator:")
print("  G_massive(k) = 1 / (phi * lambda(k) + I_i * omega^2)")
print()
print("  Heavy gear: omega small (slow rotation).")
print("  In the theta field: a massive gear = a SLOW POINT.")
print("  Spin waves BEND around it. Like light bending around mass.")
print()
print("  The bending = the 1/r^2 force.")
print("  G(r) = 1/(4*pi*r) for massless propagator in 3D.")
print()
print("  Two massive gears at distance r:")
print("  V(r) = -phi * I_1 * I_2 / (4*pi*r)")
print("  = Newtonian gravity with G_N = phi / (4*pi * m_P^2)")
print()
alpha_grav = phi / (4 * math.pi)
print(f"  Gravitational coupling: phi/(4*pi) = {alpha_grav:.6f}")
print(f"  This is at the LATTICE SCALE (Planck scale).")
print(f"  At macroscopic scale: suppressed by (a/r)^2")
print(f"  = (l_P / r)^2 = 1/phi^582 for r = Hubble")
print()

# STEP 7: Electromagnetism
print("STEP 7: ELECTROMAGNETISM")
print("-" * 50)
print()
print("  The spin waves carry angular momentum.")
print("  Conserved current: j_i = I_i * dot(theta)_i")
print("  This is a U(1) gauge symmetry (theta -> theta + const).")
print()
print("  The coupling between charges (vortices):")
print("  V_EM(r) = n_1 * n_2 / (phi * r)")
print("  = Coulomb potential with alpha = 1/(phi * 4*pi * something)")
print()

# What's the something?
# On the dodecahedron: 15*Tr(L+) = 137
# The effective EM coupling: 1/alpha = 15 * Tr(L+) = 137
# From the lattice: alpha = 1/137 comes from the TRACE of the
# inverse Laplacian, which counts the total number of independent
# propagation modes weighted by their coupling.

print("  From Tr(L+) = 137/15:")
print("  alpha = 1 / (dp * Tr(L+)) = 1/137")
print("  = the number of perpendiculars times the propagator trace")
print()
print("  Physical meaning: each of dp=15 involutions in A5 contributes")
print("  one perpendicular mode. Each mode has coupling 1/Tr(L+).")
print("  Total: dp / (dp * Tr(L+)) = 1/Tr(L+) per perpendicular.")
print("  Summed over dp perpendiculars: dp / (dp * Tr(L+)) = 1/Tr(L+).")
print("  But wait: 1/alpha = dp * Tr(L+) = 15 * 137/15 = 137.")
print("  So alpha = 1/137 exactly.")
print()

# STEP 8: Weak force
print("STEP 8: WEAK FORCE (CHIRALITY)")
print("-" * 50)
print()
print("  The Laves graph is CHIRAL (left and right forms).")
print("  Left Laves + right Laves = double gyroid.")
print()
print("  Parity violation: the lattice itself breaks L/R symmetry.")
print("  This is the WEAK FORCE origin in the gear model.")
print()
print("  Weinberg angle: the mixing between the two chiralities")
print("  sin^2(theta_W) = 3/13 = d/(F+1)")
print("  = the dimension over faces-plus-one")
print("  = the fraction of the dodecahedron that is 'one-sided'")
print()

# STEP 9: Summary
print("=" * 60)
print("THE COMPLETE MODEL")
print("=" * 60)
print()
print("  L = (I/2)*dot(theta)^2 - phi*cos(theta_i + theta_j)")
print("  on Laves graph (d=3, bipartite, chiral)")
print()
print("  CONTAINS:")
print("  Photons ......... spin waves (massless, 1/r)")
print("  Electrons ....... vortex-antivortex pairs")
print("  Quarks .......... confined vortex strings")
print("  Strong force .... vortex confinement (log potential)")
print("  EM force ........ spin-wave exchange (1/r)")
print("  Weak force ...... chirality of Laves graph (L/R)")
print("  Gravity ......... variable inertia (slow gears bend waves)")
print("  Mass ............ moment of inertia I_i")
print("  Speed of light .. lattice velocity * sqrt(phi)")
print("  alpha = 1/137 ... dp * Tr(L+) = 15 * 137/15")
print("  Relativity ...... E^2 = p^2 + m^2 (from dispersion)")
print()
print("  ONE coupling: phi")
print("  ONE lattice: Laves graph")
print("  ONE field: theta_i (gear angle)")
print()
print("  Everything else: topology + boundary conditions.")
